name: investor360
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  webview_flutter: ^4.0.1
  google_fonts: ^6.2.1
  flutter_switch: ^0.3.2
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  pin_code_fields: ^8.0.1
  flutter_recaptcha_v2_compat: ^1.0.3+3
  go_router: ^13.2.4
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  intl: ^0.17.0
  pie_chart: ^5.4.0
  #  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  super_tooltip: ^2.0.7
  fl_chart: ^0.67.0
  flutter_svg: ^2.0.10+1
  device_info_plus: ^10.1.0
  logger: ^2.2.0
  local_auth: ^2.1.7
  loader_overlay: ^4.0.0
  #animated_text_kit: ^4.2.2
  flutter_advanced_drawer: ^1.3.6
  http: ^1.2.1
  flutter_vibrate: ^1.3.0
  share_plus: ^9.0.0
  filter_list: ^1.0.3
  url_launcher: ^6.0.9
  pdf: ^3.10.8
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  syncfusion_flutter_charts: ^21.2.4
  dotted_line: ^3.2.2
  open_file: ^3.3.2
  flutter_pdfview: ^1.3.2
  platform_device_id: ^1.0.1
  package_info_plus: ^8.0.0
  root_checker_plus: ^0.0.3
  flutter_windowmanager: ^0.2.0
  flutter_secure_screen: ^0.0.1
  privacy_screen: ^0.0.6
  http_certificate_pinning: ^2.0.7
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/certificate.cer
  #   - images/a_dot_ham.jpeg
#  fonts:
#    - family: CustomFontFamily
#      fonts:
#        - asset: assets/fonts/SFUIText.ttf

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
